// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqJ2KZXF0awVcWKIjermBztWs4VwO1Qy4',
    appId: '1:315112561022:web:f77badbc4f0cf06c333b2f',
    messagingSenderId: '315112561022',
    projectId: 'myportfolio-3c47e',
    authDomain: 'myportfolio-3c47e.firebaseapp.com',
    storageBucket: 'myportfolio-3c47e.firebasestorage.app',
    measurementId: 'G-VKYQHSKZG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaxhMjVyBKVFQytwSc9jBVFz5pK4TX8M',
    appId: '1:315112561022:android:55354cdf559b7ef3333b2f',
    messagingSenderId: '315112561022',
    projectId: 'myportfolio-3c47e',
    storageBucket: 'myportfolio-3c47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomQlL67ONlrxrh-zQlwaFD6a4wmjM6lk',
    appId: '1:315112561022:ios:e1acf351e85b42f4333b2f',
    messagingSenderId: '315112561022',
    projectId: 'myportfolio-3c47e',
    storageBucket: 'myportfolio-3c47e.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAomQlL67ONlrxrh-zQlwaFD6a4wmjM6lk',
    appId: '1:315112561022:ios:e1acf351e85b42f4333b2f',
    messagingSenderId: '315112561022',
    projectId: 'myportfolio-3c47e',
    storageBucket: 'myportfolio-3c47e.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqJ2KZXF0awVcWKIjermBztWs4VwO1Qy4',
    appId: '1:315112561022:web:5a538f8ad2f11973333b2f',
    messagingSenderId: '315112561022',
    projectId: 'myportfolio-3c47e',
    authDomain: 'myportfolio-3c47e.firebaseapp.com',
    storageBucket: 'myportfolio-3c47e.firebasestorage.app',
    measurementId: 'G-W58NMPVFPQ',
  );
}
